version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3000"
    environment:
      DB_HOST: localhost
      DB_PORT: 27019
      DB_DATABASE: portfolio
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27019:27017"
    environment:
      DB_HOST: localhost
      DB_PORT: 27019
      DB_DATABASE: portfolio
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
